### ISSUE TITLE
Change footer positioning to relative in CSS

### ISSUE THREAD

**Issue by prithvidiamond1** [devilsec/website#4]
Currently, the footer position is fixed and that obscures content when it goes below the height of the fixed footer position. Changing it to relative fixes the problem which is what I assume we want since we won't be having the same length of content on each page. So letting CSS handle it relatively seems like the best bet to me. Your thoughts?

With fixed positioning:
![With fixed positioning](https://user-images.githubusercontent.com/46743102/157140942-d74906f6-e7ba-435f-8861-1f091417d521.png)

With relative positioning:
![With relative positioning](https://user-images.githubusercontent.com/46743102/157141093-60354154-4a84-4f63-87bf-07040222c504.png)

(Also ignore the video I have put up currently, I am just using a random youtube video from the DevilSec Youtube channel for testing purposes)

EDIT: Correction, well adding more content like pagination buttons messes it up again, so I don't know how to exactly fix it but its a problem that needs fixing.

**Comment by KyleMuncie** [comment]
yeah I changed the fixed footer on my page a while ago too because I realized it wasn't good. Also when I was handling this on my side, I just positioned the footer to be stuck to the bottom of my page and then I created a margin-bottom on my div with the container class. I just committed my layout a just recently so you might be able to reference it.
